# Generated by Django 3.0.6 on 2020-05-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("priority", models.IntegerField()),
            ],
            options={"ordering": ("priority",),},
        ),
        migrations.CreateModel(
            name="SubSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField(blank=True, default="")),
                ("priority", models.IntegerField()),
                (
                    "parent_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subsections",
                        to="indexpage.Section",
                    ),
                ),
            ],
            options={"ordering": ("parent_section__priority", "priority"),},
        ),
    ]
